export const TOGGLE_LOADING = 'TOGGLE_LOADING'
export const UPDATE_NOTES_STORE = 'UPDATE_NOTES_STORE'
export const GET_NOTE_TO_EDIT = 'GET_NOTE_TO_EDIT'
export const TOGGLE_REMOTE_STORAGE = 'TOGGLE_REMOTE_STORAGE'